name: Send POST to /api/notifications/comprehensive-check

on:
  schedule:
    - cron: '* * * * *' # Every minute
  workflow_dispatch:
  
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        run: |
          curl -X POST "https://mindmate.hamidijaz.dev/api/notifications/comprehensive-check"
